### ISSUE TITLE
Adding a comment in Azure Devops does not get updated in VSCode

### ISSUE THREAD

**Issue by ShaniFelig** [ankitbko/vscode-pull-request-azdo#42]
- Extension version: 0.0.21
- VSCode Version:1.55.2
- OS: Windows

Steps to Reproduce:

1. Open PR in VSCode with the extension
2.  Add comment on the PR in VSCode

You will see that even after refreshing the extension the comment that you added from Azure Devops will not appear in VSCode. Only after closing closing the PR completely and reopening it the new comment will appear

**Comment by ankitbko** [comment]
Are you adding the comment through Azure DevOps UI? Did you try refreshing the PR in VS Code?

**Comment by ShaniFelig** [comment]
Yes, I added a comment on Azure Devops UI and did not see in VSCode after refreshing the extension. Was able to resolve by reloading the window using CTRL+SHIFT+P --> reload window

**Comment by ankitbko** [comment]
So adding a comment on AzDO won't auto reflect on VS Code. This is because VS Code does not maintain an open socket connection to the AzDO. The list of comment is only fetched when PRs are loaded. You can right click on the PR and refresh it manually to see the comments. No need to reload the entire window.

**Comment by ShaniFelig** [comment]
Great, did not know that it is possible to refresh a PR. Thanks!
